#!/usr/bin/python3
import nmap

scanner = nmap.PortScanner()

ip_addr = input('Enter IP address to Scan: ')
print('IP address is:',ip_addr)

print("[+] Performing a SYN ACK Scan..")
print("Nmap Version: ", scanner.nmap_version())
scanner.scan(ip_addr, '1-1024', '-v -sS')
print(scanner.scaninfo())
print("Ip Status: ", scanner[ip_addr].state())
print(scanner[ip_addr].all_protocols())
print("Open Ports: ", scanner[ip_addr]['tcp'].keys())
